AWSTemplateFormatVersion: 2010-09-09
Description: |
The Clarusway Blog Page Application aims to deploy blog application as a web application written Django Framework on AWS Cloud Infrastructure. This infrastructure has Application Load Balancer with Auto Scaling Group of Elastic Compute Cloud (EC2) Instances and Relational Database Service (RDS) on defined VPC. Also, The Cloudfront and Route 53 services are located in front of the architecture and manage the traffic in secure. User is able to upload pictures and videos on own blog page and these are kept on S3 Bucket. This architecture will be created by Firms DevOps Guy.

Parameters:

  InputVPC:
    Description: Select the VPC 
    Type: AWS::EC2::VPC::Id

  InputSubnets:
    Description: Select the correct subnets
    Type: List<AWS::EC2::Subnet::Id>

  InputInstanceType:
    Description: Select the instance type for the EC2
    Type: String
    Default: t2.micro

  InputKeyPair:
    Description: Which key pair do you want to use
    Type: AWS::EC2::KeyPair::KeyName

  MyDbSecurityByEC2SecurityGroup:
    Description: Select the sec group for the DB instance
    Type: AWS::RDS::DBSecurityGroup
